preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "Qwen/CodeQwen1.5-7B"

inference_params:
    model: "codeqwen1.5-7b-4bit"
    seq_max_len: 32768
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda