_target_: src.baselines.data_sources.hf_data_source.HFDataSource
repos_dir: ${data_path}/repos
cache_dir: ${data_path}/hf
hub_name: tiginamaria/bug-localization
configs:
  - py
  - java
  - kt
split: test