hf_api_key: "YOUR_HF_API_KEY"
hf_tokenizer_checkpoint: "meta-llama/Llama-2-7b-chat-hf"
api_key: "YOUR_OPENAI_API_KEY"
model_name: "gpt-5-nano"
logs_dir: "./logs"
save_dir: "./predictions-gpt5nano-v5-example-guided"
max_context_toks: 2000
prompt_version: "v5_example_guided"
