# @package _global_
hydra:
  sweep:
    dir: ${data_path}/multieval
    subdir: ${run_id}
  run:
    dir: ${data_path}/eval/${run_id}

data_path: "/Users/Maria.Tigina/PycharmProjects/lca-baselines/bug_localization/data"
run_id: "anthropic-claude-3.5-sonnet_filepath"

defaults:
  - _self_
  - data_source: hf_eval
