# @package _global_
hydra:
  sweep:
    dir: ${data_path}/multirun
    subdir: ${backbone.name}_${context_composer.name}
  run:
    dir: ${data_path}/run/${backbone.name}_${context_composer.name}

data_path: "/Users/Maria.Tigina/PycharmProjects/lca-baselines/bug_localization/data"

defaults:
  - _self_
  - data_source: hf
  # filepath_imports
  # filepath
  # issue_only
  - context_composer: filepath
  # gpt-3.5
  # gpt-4o
  # gpt-4o-mini
  # llama-3.1-8b
  # llama-3.1-70b
  # llama-3.2-3b
  # qwen-2.5-7b
  # qwen-2-72b
  - backbone: gemini-pro-1.5