_target_: src.baselines.backbone.grazie_backbone.GrazieBackbone
name: anthropic-claude-3-opus
model_name: anthropic-claude-3-opus
parameters:
  seed: 76097149
  temperature: 0
context_composer: ${context_composer}
