_target_: src.baselines.backbone.grazie_backbone.GrazieBackbone
name: anthropic-claude-3.5-sonnet
model_name: anthropic-claude-3.5-sonnet
parameters:
  seed: 76097149
  temperature: 0
context_composer: ${context_composer}
