_target_: src.baselines.backbone.grazie_backbone.GrazieBackbone
name: google-gemini-pro
model_name: google-chat-gemini-pro-1.5
parameters:
  seed: 76097149
  temperature: 0
context_composer: ${context_composer}
