_target_: src.baselines.backbone.together_ai_backbone.TogetherAIBackbone
name: llama-3.1-405b
# https://docs.together.ai/docs/serverless-models
provider_name: meta-llama
model_name: Meta-Llama-3.1-405B-Instruct-Turbo
parameters:
  seed: 76097149
  temperature: 0
  response_format: {"type": "json_object"}
context_composer: ${context_composer}