_target_: src.baselines.backbone.openai_backbone.OpenAIBackbone
name: openai
# gpt-3.5-turbo-1106
# gpt-4o
# gpt-4o-mini
model_name: gpt-4o
parameters:
  seed: 76097149
  temperature: 0
  response_format: {"type": "json_object"}
context_composer: ${context_composer}
