name: Style and typing checks for CMG

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2

      - name: Go to CMG folder
        run: |
          cd commit_message_generation

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Lint with Black
        run: |
          poetry run black -l 120 . --check

      - name: Check import styling with isort
        run: |
          poetry run isort --profile black . --check

      - name: Check types with mypy
        run: |
          poetry run mypy .